version: '3.9'

services:
  app:
    image: 'account-query:latest'
    build:
      context: .
    ports:
      - "5001:5001"
    depends_on:
      - database
    environment:
      - spring.datasource.url=jdbc:mysql://database:3306/bankAccount?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - server.port=5001
      - spring.datasource.username=root
      - spring.datasource.password=ippavlova_1990
    networks:
      - bankQuery

  database:
    container_name: mysql-database
    image: 'mysql:latest'
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_PASSWORD: ippavlova_1990
      MYSQL_ROOT_PASSWORD: ippavlova_1990
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - bankQuery
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10


networks:
  bankQuery:

volumes:
  db-data: